# Generated by Django 5.2.2 on 2025-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
