# Generated by Django 5.2.2 on 2025-06-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0003_basvuru'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru',
            name='bank_asset_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='commercial_assets_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='income_annum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='loan_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='luxury_assets_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='no_of_dependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='residential_assets_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='self_employed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
