# Generated by Django 5.2.2 on 2025-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0004_basvuru_bank_asset_value_basvuru_cibil_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru',
            name='altin_kuru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='eur_kuru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='usd_kuru',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
